<?php
/**
* dasENIGMA.
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://codecanyon.net/licenses/regular
*
* =================================================================
*                 MAGENTO EDITION USAGE NOTICE
* =================================================================
* This package designed for Magento community edition
* dasENIGMA does not guarantee correct work of this extension
* on any other Magento edition except Magento community edition.
* dasENIGMA does not provide extension support in case of
* incorrect edition usage.
* =================================================================
*
* @category   Enigma
* @package    Enigma_AdminLogger
* @version    1.0
* @copyright  Copyright (c) 2014 dasENIGMA. (http://codecanyon.net/user/dasEnigma/portfolio?ref=dasEnigma)
* @license    http://codecanyon.net/licenses/regular
*/
?>
<div class="entry-edit">
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Admin Watch_Logger')?></h3></td>
            <td align="right">
                <button onclick="document.location.href='<?php echo $this->getPruneUrl(); ?>'" class="scalable" type="button"><span><?php echo $this->__('Prune Logs')?></span></button>            
                <button onclick="document.location.href='<?php echo $this->getClearUrl(); ?>'" class="scalable" type="button"><span><?php echo $this->__('Clear Logs')?></span></button>            
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getGridParentHtml() ?>
</div>