<?php
/**
 * Open Biz Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file OPEN-BIZ-LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mageconsult.net/terms-and-conditions
 *
 * @category   Magecon
 * @package    Magecon_Rma
 * @version    1.0.0
 * @copyright  Copyright (c) 2013 Open Biz Ltd (http://www.mageconsult.net)
 * @license    http://mageconsult.net/terms-and-conditions
 */
?> 
<?php $rma = $this->getRma() ?>
<div id="rma_history_block">
    <div id="history_form" class="rma_history_block">
        <span class="field-row">
            <label class="normal" for="status"><?php echo Mage::helper('rma')->__('Status') ?></label><br/>
            <select name="status" class="select" id="history_status">
                <?php foreach ($this->getStatuses() as $_label): ?>
                    <option value="<?php echo $_label->getCode() ?>"<?php if ($_label->getCode() == $rma->getStatusCode()): ?> selected="selected"<?php endif; ?>><?php echo $_label->getStatus() ?></option>
                <?php endforeach; ?>
            </select>
        </span>
        <span class="field-row">
            <label class="normal" for="history_comment"><?php echo Mage::helper('rma')->__('Comment') ?></label>
            <textarea name="history_comment" rows="3" cols="5" style="height:6em; width:99%;" id="history_comment"></textarea>
        </span>
        <div class="f-left">
            <?php if ($this->canSendCommentEmail()): ?>
                <input name="is_customer_notified" type="checkbox" id="history_notify" value="1" /><label class="normal" for="is_customer_notified"> <?php echo Mage::helper('rma')->__('Notify Customer by Email') ?></label><br />
            <?php endif; ?>
            <input name="is_visible_on_front" type="checkbox" id="history_visible" value="1" /><label class="normal" for="is_visible_on_front"> <?php echo Mage::helper('rma')->__('Visible on Frontend') ?></label>
            <input type="hidden" name="rma_id" value="<?php echo $rma->getRmaId(); ?>" />
        </div>
        <div class="f-right">
            <?php echo $this->getChildHtml('submit_button') ?>
        </div>
        <div class="clear"></div>
    </div>
    <div class="divider"></div>
    <ul class="note-list">
        <?php foreach (Mage::getModel('rma/history')->getCollection()->addAttributeToFilter('rma_id', array('eq' => $rma->getRmaId())) as $_item): ?>
            <li>
                <strong><?php echo $this->helper('core')->formatDate($_item->getCreationDate(), 'medium') ?></strong>
                <?php echo $this->helper('core')->formatTime($_item->getCreationDate(), 'medium') ?><span class="separator">|</span><strong><?php echo $_item->getStatus() ?></strong><br/><small><?php echo $this->helper('sales')->__('Customer') ?>
                    <strong class="subdue">
                        <?php if ($_item->getNotified()): ?>
                            <?php echo $this->helper('rma')->__('Notified') ?>
                            <img src="<?php echo $this->getSkinUrl('images/ico_success.gif') ?>" width="16" height="16" alt="" />
                        <?php else: ?>
                            <?php echo $this->helper('rma')->__('Not Notified') ?>
                        <?php endif; ?>
                    </strong></small>
                <?php if ($_item->getComment()): ?>
                    <br/><?php echo $this->escapeHtml($_item->getComment(), array('b', 'br', 'strong', 'i', 'u')) ?>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <script type="text/javascript">
        if($('status'))$('status').update('<?php echo $rma->getStatus() ?>');
    </script>
</div>