<?php
/**
 * Open Biz Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file OPEN-BIZ-LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mageconsult.net/terms-and-conditions
 *
 * @category   Magecon
 * @package    Magecon_Rma
 * @version    1.0.0
 * @copyright  Copyright (c) 2013 Open Biz Ltd (http://www.mageconsult.net)
 * @license    http://mageconsult.net/terms-and-conditions
 */
?>
<?php $rma = $this->getRma() ?>
<?php
$rmaDate = $this->formatDate($rma->getCreationDate(), 'medium', true);
$orderDate = $this->formatDate($rma->getScanDate(), 'medium', true);
$modificationDate = $this->formatDate($rma->getModificationDate(), 'medium', true);
?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('rma')->__('Request Information') ?> 
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('Order #') ?></label></td>
                    <td class="value"><strong><?php echo $rma->getRealOrderId(); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('RMA #') ?></label></td>
                    <?php //if (Mage::getStoreConfig('customerrefunds/settings/rma_id')) :  ?>
                    <!--<td class="value"><input type="text" name="rma_id" value="<?php echo $rma->getRmaId(); ?>" /></td>-->
                    <?php //else : ?>
                    <td class="value"><strong><?php echo $rma->getRmaId(); ?></strong></td>
                    <?php //endif; ?>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('Order Date') ?></label></td>
                    <td class="value"><strong><?php echo $orderDate ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('RMA Date') ?></label></td>
                    <td class="value"><strong><?php echo $rmaDate ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('RMA Last Updated') ?></label></td>
                    <td class="value"><strong><?php echo $modificationDate; ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('rma')->__('Refund Status') ?></label></td>
                    <td class="value"><strong><?php echo $rma->getStatus(); ?></strong></td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('rma')->__('Account information') ?> 
        </div>
        <div class="fieldset">
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('rma')->__('Customer Name') ?></label></td>
                        <td class="value">
                            <?php if ($_customerUrl = $this->getCustomerViewUrl()) : ?>
                                <a href="<?php echo $_customerUrl ?>" target="_blank"><strong><?php echo $this->htmlEscape($rma->getCustomerName()) ?></strong></a>
                            <?php else: ?>
                                <strong><?php echo $this->htmlEscape($rma->getCustomerName()) ?></strong>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('rma')->__('Email') ?></label></td>
                        <td class="value"><a href="mailto:<?php Mage::getModel('customer/customer')->load($rma->getCustomerId())->getEmail(); ?>"><strong><?php echo Mage::getModel('customer/customer')->load($rma->getCustomerId())->getEmail(); ?></strong></a></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="clear"></div>
<div>
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo Mage::helper('sales')->__('Comments History') ?></h4>
        </div>
        <fieldset><?php echo $this->getChildHtml('rma_history') ?></fieldset>
    </div>
</div>
<div class="clear"></div>