<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Sarp2
 * @version    2.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php echo $this->getChildHtml('native_notification_toolbar'); ?>
<?php if (Mage::helper('aw_sarp2')->isEnabled()) : ?>
    <?php foreach (Mage::helper('aw_sarp2/notification')->getNotification() as $notification) : ?>
        <div class="notification-global-notice notification-global">
            <?php echo $notification; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>