<?php
/**
 * Merchant Protocol
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Merchant Protocol Commercial License (MPCL 1.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://merchantprotocol.com/commercial-license/
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@merchantprotocol.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade to newer
 * versions in the future. If you wish to customize the extension for your
 * needs please refer to http://www.merchantprotocol.com for more information.
 *
 * @category   MP
 * @package    MP_AdvancedDataflow
 * @copyright  Copyright (c) 2006-2016 Merchant Protocol LLC. and affiliates (https://merchantprotocol.com/)
 * @license    https://merchantprotocol.com/commercial-license/  Merchant Protocol Commercial License (MPCL 1.0)
 */

/**
 * Order resource setup model
 *
 * @category   Innoexts
 * @package    Innoexts_AdvancedDataflow
 * @author     Innoexts Team <developers@innoexts.com>
 */
class Innoexts_AdvancedDataflow_Model_Entity_Setup extends Mage_Eav_Model_Entity_Setup
{
    /**
     * Get default entities
     * 
     * @return array
     */
    public function getDefaultEntities()
    {
        return array(
            'sales_order' => array(
                'entity_model'                  => '', 
                'table'                         => '', 
                'increment_model'               => '', 
                'increment_per_store'           => '0', 
                'additional_attribute_table'    => '', 
                'entity_attribute_collection'   => '', 
                'attributes' => array(
                    'entity_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Entity Id', 
                        'input'     => 'text', 
                    ), 
                    'increment_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Increment Id', 
                        'input'     => 'text', 
                        'unique'    => '1', 
                    ), 
                    'real_order_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Real Order Id', 
                        'input'     => 'text', 
                        'unique'    => '1', 
                    ), 
                    'state' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'State', 
                        'input'     => 'text', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_status_state', 
                    ), 
                    'status' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Status', 
                        'input'     => 'text', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_status', 
                    ), 
                    'hold_before_state' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Hold Before State', 
                        'input'     => 'text', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_status_state', 
                    ), 
                    'hold_before_status' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Hold Before Status', 
                        'input'     => 'text', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_status', 
                    ), 
                    'coupon_code' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Coupon Code', 
                        'input'     => 'text', 
                    ), 
                    'protect_code' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Protect Code', 
                        'input'     => 'text', 
                    ), 
                    'shipping_method' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Shipping Method', 
                        'input'     => 'text', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_shipping_method', 
                    ), 
                    'shipping_description' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Shipping Description', 
                        'input'     => 'text', 
                    ), 
                    'discount_description' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Discount Description', 
                        'input'     => 'text', 
                    ), 
                    'is_virtual' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Is Virtual', 
                        'input'     => 'text', 
                    	'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'store_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Store Id', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_store', 
                    ), 
                    'store_name' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Store Name', 
                        'input'     => 'text', 
                    ), 
                    'customer_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Customer Id', 
                        'input'     => 'text', 
                    ), 
                    'customer_is_guest' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Customer Is Guest', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'customer_note_notify' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Customer Note Notify', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'customer_email' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Customer Email', 
                        'input'     => 'text', 
                    ), 
                    'customer_firstname' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Customer Firstname', 
                        'input'     => 'text', 
                    ), 
                    'customer_lastname' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Customer Lastname', 
                        'input'     => 'text', 
                    ), 
                    'customer_middlename' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Customer Middlename', 
                        'input'     => 'text', 
                    ), 
                    'customer_prefix' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Customer Prefix', 
                        'input'     => 'text', 
                    ), 
                    'customer_suffix' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Customer Suffix', 
                        'input'     => 'text', 
                    ), 
                    'customer_taxvat' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Customer Taxvat', 
                        'input'     => 'text', 
                    ), 
                    'customer_dob' => array(
                        'type'      => 'datetime', 
                        'required'  => false, 
                        'label'     => 'Customer Dob', 
                        'input'     => 'date', 
                    ), 
                    'customer_gender' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Customer Gender', 
                        'input'     => 'text', 
                    ), 
                    'customer_note' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Customer Note', 
                        'input'     => 'text', 
                    ), 
                    'ext_customer_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Ext Customer Id', 
                        'input'     => 'text', 
                    ), 
                    'customer_group_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Customer Group Id', 
                        'input'     => 'text', 
                    ), 
                    'currency_base_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Currency Base Id', 
                        'input'     => 'text', 
                    ), 
                    'relation_child_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Relation Child Id', 
                        'input'     => 'text', 
                    ), 
                    'relation_child_real_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Relation Child Real Id', 
                        'input'     => 'text', 
                    ), 
                    'relation_parent_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Relation Parent Id', 
                        'input'     => 'text', 
                    ), 
                    'relation_parent_real_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Relation Parent Real Id', 
                        'input'     => 'text', 
                    ), 
                    'original_increment_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Original Increment Id', 
                        'input'     => 'text', 
                    ), 
                    'edit_increment' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Edit Increment', 
                        'input'     => 'text', 
                    ), 
                    'quote_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Quote Id', 
                        'input'     => 'text', 
                    ), 
                    'quote_address_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Quote Address Id', 
                        'input'     => 'text', 
                    ), 
                    'gift_message_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Gift Message Id', 
                        'input'     => 'text', 
                    ), 
                    'can_ship_partially' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Can Ship Partially', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'can_ship_partially_item' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Can Ship Partially Item', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'forced_do_shipment_with_invoice' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Forced Do Shipment With Invoice', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'paypal_ipn_customer_notified' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Paypal Ipn Customer Notified', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'is_hold' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Is Hold', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'is_multi_payment' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Is Multi Payment', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'email_sent' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Email Sent', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'payment_authorization_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Payment Authorization Amount', 
                        'input'     => 'text', 
                    ), 
                    'payment_authorization_expiration' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Payment Authorization Expiration', 
                        'input'     => 'text', 
                    ), 
                    'weight' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Weight', 
                        'input'     => 'text', 
                    ), 
                    'total_item_count' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Total Item Count', 
                        'input'     => 'text', 
                    ), 
                    'tax_percent' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Percent', 
                        'input'     => 'text', 
                    ), 
                    'remote_ip' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Remote Ip', 
                        'input'     => 'text', 
                    ), 
                    'x_forwarded_for' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'X Forwarded For', 
                        'input'     => 'text', 
                    ), 
                    'applied_rule_ids' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Applied Rule Ids', 
                        'input'     => 'text', 
                    ), 
                    'ext_order_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Ext Order Id', 
                        'input'     => 'text', 
                    ), 
                    'tracking_numbers' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Tracking Numbers', 
                        'input'     => 'text', 
                    ), 
                    'created_at' => array(
                        'type'      => 'datetime', 
                        'required'  => false, 
                        'label'     => 'Created At', 
                        'input'     => 'date', 
                    ), 
                    'updated_at' => array(
                        'type'      => 'datetime', 
                        'required'  => false, 
                        'label'     => 'Updated At', 
                        'input'     => 'date', 
                    ), 
                    'base_currency_code' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Base Currency Code', 
                        'input'     => 'text', 
                        'default'   => 'USD', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_currency', 
                    ), 
                    'currency_code' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Currency Code', 
                        'input'     => 'text', 
                        'default'   => 'USD', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_currency', 
                    ), 
                    'store_currency_code' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Store Currency Code', 
                        'input'     => 'text', 
                        'default'   => 'USD', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_currency', 
                    ), 
                    'order_currency_code' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Order Currency Code', 
                        'input'     => 'text', 
                        'default'   => 'USD', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_currency', 
                    ), 
                    'global_currency_code' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Global Currency Code', 
                        'input'     => 'text', 
                        'default'   => 'USD', 
                        'source'    => 'advanceddataflow/sales_order_attribute_source_currency', 
                    ), 
                    
                    'currency_rate' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Currency Rate', 
                        'input'     => 'text', 
                    ), 
                    'base_to_global_rate' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base To Global Rate', 
                        'input'     => 'text', 
                    ), 
                    'base_to_order_rate' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base To Order Rate', 
                        'input'     => 'text', 
                    ), 
                    'store_to_base_rate' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Store To Base Rate', 
                        'input'     => 'text', 
                    ), 
                    'store_to_order_rate' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Store To Order Rate', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Amount', 
                        'input'     => 'text', 
                    ), 
                    'shipping_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_subtotal' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Subtotal', 
                        'input'     => 'text', 
                    ), 
                    'subtotal' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Subtotal', 
                        'input'     => 'text', 
                    ), 
                    'base_grand_total' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Grand Total', 
                        'input'     => 'text', 
                    ), 
                    'grand_total' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Grand Total', 
                        'input'     => 'text', 
                    ), 
                    'base_discount_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Discount Amount', 
                        'input'     => 'text', 
                    ), 
                    'discount_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Discount Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_discount_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Discount Canceled', 
                        'input'     => 'text', 
                    ), 
                    'discount_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Discount Canceled', 
                        'input'     => 'text', 
                    ), 
                    'base_discount_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Discount Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'discount_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Discount Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_discount_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Discount Refunded', 
                        'input'     => 'text', 
                    ), 
                    'discount_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Discount Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Canceled', 
                        'input'     => 'text', 
                    ), 
                    'shipping_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Canceled', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'shipping_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Refunded', 
                        'input'     => 'text', 
                    ), 
                    'shipping_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'shipping_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'shipping_tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_discount_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Discount Amount', 
                        'input'     => 'text', 
                    ), 
                    'shipping_discount_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Discount Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_incl_tax' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Incl Tax', 
                        'input'     => 'text', 
                    ), 
                    'shipping_incl_tax' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Incl Tax', 
                        'input'     => 'text', 
                    ), 
                    'base_subtotal_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Subtotal Canceled', 
                        'input'     => 'text', 
                    ), 
                    'subtotal_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Subtotal Canceled', 
                        'input'     => 'text', 
                    ), 
                    'base_subtotal_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Subtotal Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'subtotal_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Subtotal Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_subtotal_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Subtotal Refunded', 
                        'input'     => 'text', 
                    ), 
                    'subtotal_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Subtotal Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_tax_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Tax Canceled', 
                        'input'     => 'text', 
                    ), 
                    'tax_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Canceled', 
                        'input'     => 'text', 
                    ), 
                    'base_tax_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Tax Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'tax_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_hidden_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Hidden Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'hidden_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Hidden Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_hidden_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Hidden Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'shipping_hidden_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Hidden Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_hidden_tax_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Hidden Tax Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'hidden_tax_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Hidden Tax Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_hidden_tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Hidden Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'hidden_tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Hidden Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_total_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Canceled', 
                        'input'     => 'text', 
                    ), 
                    'total_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Total Canceled', 
                        'input'     => 'text', 
                    ), 
                    'base_total_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'total_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Total Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_total_offline_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Offline Refunded', 
                        'input'     => 'text', 
                    ), 
                    'total_offline_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Total Offline Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_total_online_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Online Refunded', 
                        'input'     => 'text', 
                    ), 
                    'total_online_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Total Online Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_total_paid' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Paid', 
                        'input'     => 'text', 
                    ), 
                    'total_paid' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Total Paid', 
                        'input'     => 'text', 
                    ), 
                    'base_total_qty_ordered' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Qty Ordered', 
                        'input'     => 'text', 
                    ), 
                    'total_qty_ordered' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Total Qty Ordered', 
                        'input'     => 'text', 
                    ), 
                    'base_total_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Refunded', 
                        'input'     => 'text', 
                    ), 
                    'total_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Total Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_subtotal_incl_tax' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Subtotal Incl Tax', 
                        'input'     => 'text', 
                    ), 
                    'subtotal_incl_tax' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Subtotal Incl Tax', 
                        'input'     => 'text', 
                    ), 
                    'base_adjustment_negative' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Adjustment Negative', 
                        'input'     => 'text', 
                    ), 
                    'adjustment_negative' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Adjustment Negative', 
                        'input'     => 'text', 
                    ), 
                    'base_adjustment_positive' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Adjustment Positive', 
                        'input'     => 'text', 
                    ), 
                    'adjustment_positive' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Adjustment Positive', 
                        'input'     => 'text', 
                    ), 
                    'base_total_due' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Due', 
                        'input'     => 'text', 
                    ), 
                    'total_due' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Total Due', 
                        'input'     => 'text', 
                    ), 
                    'base_custbalance_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Custbalance Amount', 
                        'input'     => 'text', 
                    ), 
                    'custbalance_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Custbalance Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_total_invoiced_cost' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Total Invoiced Cost', 
                        'input'     => 'text', 
                    ), 
                    /*
                    'billing_address_id' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Billing Address Id', 
                        'input'     => 'text', 
                    ), 
                    'shipping_address_id' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Address Id', 
                        'input'     => 'text', 
                    ), 
                    */
                ), 
            ), 
            'sales_order_address' => array(
                'entity_model'                  => '', 
                'table'                         => '', 
                'increment_model'               => '', 
                'increment_per_store'           => '0', 
                'additional_attribute_table'    => '', 
                'entity_attribute_collection'   => '', 
                'attributes' => array(
            		'entity_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Entity Id', 
                        'input'     => 'text', 
                    ), 
                    'parent_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Parent Id', 
                        'input'     => 'text', 
                    ), 
                    'customer_address_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Customer Address Id', 
                        'input'     => 'text', 
                    ), 
                    'quote_address_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Quote Address Id', 
                        'input'     => 'text', 
                    ), 
                    'customer_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Customer Id', 
                        'input'     => 'text', 
                    ), 
                    'address_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Address Id', 
                        'input'     => 'text', 
                    ), 
                    'gift_message_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Gift Message Id', 
                        'input'     => 'text', 
                    ), 
                    'tax_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Tax Id', 
                        'input'     => 'text', 
                    ), 
                    'address_type' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Address Type', 
                        'input'     => 'text', 
                    ), 
                    'prefix' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Prefix', 
                        'input'     => 'text', 
                    ), 
                    'firstname' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Firstname', 
                        'input'     => 'text', 
                    ), 
                    'middlename' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Middlename', 
                        'input'     => 'text', 
                    ), 
                    'lastname' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Lastname', 
                        'input'     => 'text', 
                    ), 
                    'suffix' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Suffix', 
                        'input'     => 'text', 
                    ), 
                    'country_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Country Id', 
                        'input'     => 'text', 
                        'source'    => 'advanceddataflow/sales_order_address_attribute_source_country', 
                    ), 
                    'region_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Region Id', 
                        'input'     => 'text', 
                        'source'    => 'advanceddataflow/sales_order_address_attribute_source_region', 
                    ), 
                    'region' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Region', 
                        'input'     => 'text', 
                    ), 
                    'email' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Email', 
                        'input'     => 'text', 
                    ), 
                    'company' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Company', 
                        'input'     => 'text', 
                    ), 
                    'street' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Street', 
                        'input'     => 'text', 
                    ), 
                    'city' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'City', 
                        'input'     => 'text', 
                    ), 
                    'postcode' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Postcode', 
                        'input'     => 'text', 
                    ), 
                    'telephone' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Telephone', 
                        'input'     => 'text', 
                    ), 
                    'fax' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Fax', 
                        'input'     => 'text', 
                    ), 
                ), 
            ), 
            'sales_order_item' => array(
                'entity_model'                  => '', 
                'table'                         => '', 
                'increment_model'               => '', 
                'increment_per_store'           => '0', 
                'additional_attribute_table'    => '', 
                'entity_attribute_collection'   => '', 
                'attributes' => array(
                    'item_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Item Id', 
                        'input'     => 'text', 
                    ), 
                    'order_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Order Id', 
                        'input'     => 'text', 
                    ), 
                    'parent_item_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Parent Item Id', 
                        'input'     => 'text', 
                    ), 
                    'quote_item_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Quote Item Id', 
                        'input'     => 'text', 
                    ), 
                    'store_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Store Id', 
                        'input'     => 'text', 
                    ), 
                    'created_at' => array(
                        'type'      => 'datetime', 
                        'required'  => false, 
                        'label'     => 'Created At', 
                        'input'     => 'date', 
                    ), 
                    'updated_at' => array(
                        'type'      => 'datetime', 
                        'required'  => false, 
                        'label'     => 'Updated At', 
                        'input'     => 'date', 
                    ), 
                    'product_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Product Id', 
                        'input'     => 'text', 
                    ), 
                    'product_type' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Product Type', 
                        'input'     => 'text', 
                    ), 
                    'product_options' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Product Options', 
                        'input'     => 'text', 
                    ), 
                    'sku' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Sku', 
                        'input'     => 'text', 
                    ), 
                    'name' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Name', 
                        'input'     => 'text', 
                    ), 
                    'description' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Description', 
                        'input'     => 'text', 
                    ), 
                    'is_virtual' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Is Virtual', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'is_qty_decimal' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Is Qty Decimal', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'free_shipping' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Free Shipping', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'no_discount' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'No Discount', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'is_nominal' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Is Nominal', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'row_weight' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Row Weight', 
                        'input'     => 'text', 
                    ), 
                    'weight' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Weight', 
                        'input'     => 'text', 
                    ), 
                    'qty_backordered' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Qty Backordered', 
                        'input'     => 'text', 
                    ), 
                    'qty_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Qty Canceled', 
                        'input'     => 'text', 
                    ), 
                    'qty_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Qty Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'qty_ordered' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Qty Ordered', 
                        'input'     => 'text', 
                    ), 
                    'qty_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Qty Refunded', 
                        'input'     => 'text', 
                    ), 
                    'qty_shipped' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Qty Shipped', 
                        'input'     => 'text', 
                    ), 
                    'gift_message_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Gift Message Id', 
                        'input'     => 'text', 
                    ), 
                    'gift_message_available' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Gift Message Available', 
                        'input'     => 'text', 
                    ), 
                    'ext_order_item_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Ext Order Item Id', 
                        'input'     => 'text', 
                    ), 
                    'applied_rule_ids' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Applied Rule Ids', 
                        'input'     => 'text', 
                    ), 
                    'additional_data' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Additional Data', 
                        'input'     => 'text', 
                    ), 
                    'weee_tax_applied' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Weee Tax Applied', 
                        'input'     => 'text', 
                    ), 
                    'locked_do_invoice' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Locked Do Invoice', 
                        'input'     => 'text', 
                    ), 
                    'locked_do_ship' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Locked Do Ship', 
                        'input'     => 'text', 
                    ), 
                    'discount_percent' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Discount Percent', 
                        'input'     => 'text', 
                    ), 
                    'tax_percent' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Percent', 
                        'input'     => 'text', 
                    ), 
                    'base_cost' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Cost', 
                        'input'     => 'text', 
                    ), 
                    'price' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Price', 
                        'input'     => 'text', 
                    ), 
                    'base_price' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Price', 
                        'input'     => 'text', 
                    ), 
                    'original_price' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Original Price', 
                        'input'     => 'text', 
                    ), 
                    'base_original_price' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Original Price', 
                        'input'     => 'text', 
                    ), 
                    'tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'tax_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_tax_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Tax Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'discount_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Discount Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_discount_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Discount Amount', 
                        'input'     => 'text', 
                    ), 
                    'discount_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Discount Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_discount_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Discount Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'amount_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Amount Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_amount_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Amount Refunded', 
                        'input'     => 'text', 
                    ), 
                    'row_total' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Row Total', 
                        'input'     => 'text', 
                    ), 
                    'base_row_total' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Row Total', 
                        'input'     => 'text', 
                    ), 
                    'row_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Row Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_row_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Row Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_tax_before_discount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Tax Before Discount', 
                        'input'     => 'text', 
                    ), 
                    'tax_before_discount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Before Discount', 
                        'input'     => 'text', 
                    ), 
                    'weee_tax_applied_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Weee Tax Applied Amount', 
                        'input'     => 'text', 
                    ), 
                    'weee_tax_applied_row_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Weee Tax Applied Row Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_weee_tax_applied_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Weee Tax Applied Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_weee_tax_applied_row_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Weee Tax Applied Row Amount', 
                        'input'     => 'text', 
                    ), 
                    'weee_tax_disposition' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Weee Tax Disposition', 
                        'input'     => 'text', 
                    ), 
                    'weee_tax_row_disposition' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Weee Tax Row Disposition', 
                        'input'     => 'text', 
                    ), 
                    'base_weee_tax_disposition' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Weee Tax Disposition', 
                        'input'     => 'text', 
                    ), 
                    'base_weee_tax_row_disposition' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Weee Tax Row Disposition', 
                        'input'     => 'text', 
                    ), 
                    'hidden_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Hidden Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_hidden_tax_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Hidden Tax Amount', 
                        'input'     => 'text', 
                    ), 
                    'hidden_tax_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Hidden Tax Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'base_hidden_tax_invoiced' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Hidden Tax Invoiced', 
                        'input'     => 'text', 
                    ), 
                    'hidden_tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Hidden Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_hidden_tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Hidden Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'tax_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Canceled', 
                        'input'     => 'text', 
                    ), 
                    'hidden_tax_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Hidden Tax Canceled', 
                        'input'     => 'text', 
                    ), 
                    'tax_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Tax Refunded', 
                        'input'     => 'text', 
                    ), 
                    'price_incl_tax' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Price Incl Tax', 
                        'input'     => 'text', 
                    ), 
                    'base_price_incl_tax' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Price Incl Tax', 
                        'input'     => 'text', 
                    ), 
                    'row_total_incl_tax' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Row Total Incl Tax', 
                        'input'     => 'text', 
                    ), 
                    'base_row_total_incl_tax' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Row Total Incl Tax', 
                        'input'     => 'text', 
                    ), 
                ), 
            ), 
            'sales_order_payment' => array(
                'entity_model'                  => '', 
                'table'                         => '', 
                'increment_model'               => '', 
                'increment_per_store'           => '0', 
                'additional_attribute_table'    => '', 
                'entity_attribute_collection'   => '', 
                'attributes' => array(
                    'entity_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Entity Id', 
                        'input'     => 'text', 
                    ), 
                    'parent_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Parent Id', 
                        'input'     => 'text', 
                    ), 
                    'quote_payment_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Quote Payment Id', 
                        'input'     => 'text', 
                    ), 
                    'customer_payment_id' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Customer Payment Id', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Amount', 
                        'input'     => 'text', 
                    ), 
                    'shipping_amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Amount', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_captured' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Captured', 
                        'input'     => 'text', 
                    ), 
                    'shipping_captured' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Captured', 
                        'input'     => 'text', 
                    ), 
                    'base_shipping_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Shipping Refunded', 
                        'input'     => 'text', 
                    ), 
                    'shipping_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Shipping Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_amount_authorized' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Amount Authorized', 
                        'input'     => 'text', 
                    ), 
                    'amount_authorized' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Amount Authorized', 
                        'input'     => 'text', 
                    ), 
                    'base_amount_paid' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Amount Paid', 
                        'input'     => 'text', 
                    ), 
                    'amount_paid' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Amount Paid', 
                        'input'     => 'text', 
                    ), 
                    'base_amount_paid_online' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Amount Paid Online', 
                        'input'     => 'text', 
                    ), 
                    'amount_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Amount Refunded', 
                        'input'     => 'text', 
                    ), 
                    'base_amount_refunded_online' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Amount Refunded Online', 
                        'input'     => 'text', 
                    ), 
                    'base_amount_refunded' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Amount Refunded', 
                        'input'     => 'text', 
                    ), 
                    'amount_ordered' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Amount Ordered', 
                        'input'     => 'text', 
                    ), 
                    'base_amount_ordered' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Amount Ordered', 
                        'input'     => 'text', 
                    ), 
                    'amount_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Amount Canceled', 
                        'input'     => 'text', 
                    ), 
                    'base_amount_canceled' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Base Amount Canceled', 
                        'input'     => 'text', 
                    ), 
                    'amount' => array(
                        'type'      => 'decimal', 
                        'required'  => false, 
                        'label'     => 'Amount', 
                        'input'     => 'text', 
                    ), 
                    'cc_trans_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Trans Id', 
                        'input'     => 'text', 
                    ), 
                    'cc_status' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Status', 
                        'input'     => 'text', 
                    ), 
                    'cc_status_description' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Status Description', 
                        'input'     => 'text', 
                    ), 
                    'cc_cid_status' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Cid Status', 
                        'input'     => 'text', 
                    ), 
                    'cc_avs_status' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Avs Status', 
                        'input'     => 'text', 
                    ), 
                    'cc_owner' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Owner', 
                        'input'     => 'text', 
                    ), 
                    'cc_type' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Type', 
                        'input'     => 'text', 
                    ), 
                    'cc_exp_year' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Exp Year', 
                        'input'     => 'text', 
                    ), 
                    'cc_exp_month' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Exp Month', 
                        'input'     => 'text', 
                    ), 
                    'cc_last4' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Last4', 
                        'input'     => 'text', 
                    ), 
                    'cc_secure_verify' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Secure Verify', 
                        'input'     => 'text', 
                    ), 
                    'cc_ss_start_year' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Ss Start Year', 
                        'input'     => 'text', 
                    ), 
                    'cc_ss_start_month' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Ss Start Month', 
                        'input'     => 'text', 
                    ), 
                    'cc_ss_issue' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Ss Issue', 
                        'input'     => 'text', 
                    ), 
                    'cc_approval' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Approval', 
                        'input'     => 'text', 
                    ), 
                    'cc_number_enc' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Number Enc', 
                        'input'     => 'text', 
                    ), 
                    'cc_raw_request' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Cc Raw Request', 
                        'input'     => 'text', 
                    ), 
                    'cc_debug_request_body' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Debug Request Body', 
                        'input'     => 'text', 
                    ), 
                    'cc_raw_response' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Cc Raw Response', 
                        'input'     => 'text', 
                    ), 
                    'cc_debug_response_body' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Debug Response Body', 
                        'input'     => 'text', 
                    ), 
                    'cc_debug_response_serialized' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cc Debug Response Serialized', 
                        'input'     => 'text', 
                    ), 
                    'method' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Method', 
                        'input'     => 'text', 
                    ), 
                    'address_status' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Address Status', 
                        'input'     => 'text', 
                    ), 
                    'additional_data' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Additional Data', 
                        'input'     => 'text', 
                    ), 
                    'additional_information' => array(
                        'type'      => 'text', 
                        'required'  => false, 
                        'label'     => 'Additional Information', 
                        'input'     => 'text', 
                    ), 
                    'protection_eligibility' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Protection Eligibility', 
                        'input'     => 'text', 
                    ), 
                    'last_trans_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Last Trans Id', 
                        'input'     => 'text', 
                    ), 
                    'account_status' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Account Status', 
                        'input'     => 'text', 
                    ), 
                    'echeck_type' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Echeck Type', 
                        'input'     => 'text', 
                    ), 
                    'echeck_bank_name' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Echeck Bank Name', 
                        'input'     => 'text', 
                    ), 
                    'echeck_account_type' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Echeck Account Type', 
                        'input'     => 'text', 
                    ), 
                    'echeck_account_name' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Echeck Account Name', 
                        'input'     => 'text', 
                    ), 
                    'echeck_routing_number' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Echeck Routing Number', 
                        'input'     => 'text', 
                    ), 
                    'ideal_issuer_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Ideal Issuer Id', 
                        'input'     => 'text', 
                    ), 
                    'ideal_issuer_title' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Ideal Issuer Title', 
                        'input'     => 'text', 
                    ), 
                    'ideal_transaction_checked' => array(
                        'type'      => 'int', 
                        'required'  => false, 
                        'label'     => 'Ideal Transaction Checked', 
                        'input'     => 'text', 
                        'source'    => 'eav/entity_attribute_source_boolean', 
                    ), 
                    'paybox_request_number' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Paybox Request Number', 
                        'input'     => 'text', 
                    ), 
                    'paybox_question_number' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Paybox Question Number', 
                        'input'     => 'text', 
                    ), 
                    'flo2cash_account_id' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Flo2cash Account Id', 
                        'input'     => 'text', 
                    ), 
                    'cybersource_token' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Cybersource Token', 
                        'input'     => 'text', 
                    ), 
                    'po_number' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Po Number', 
                        'input'     => 'text', 
                    ), 
                    'anet_trans_method' => array(
                        'type'      => 'varchar', 
                        'required'  => false, 
                        'label'     => 'Anet Trans Method', 
                        'input'     => 'text', 
                    ), 
                ), 
            ), 
        );
    }
}
